park_homepage:
    path:     /hello/{name}
    defaults: { _controller: ParkBundle:Default:index }

park_toto:
    path:     /toto/{name}
    defaults: { _controller: ParkBundle:Default:toto }
    requirements:
        name:    "[a-zA-Z]+"

park_list:
    path:     /list
    defaults: { _controller: ParkBundle:Computer:list }